---
ignore:
  - .venv

rules:

  braces:
    forbid: false
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: -1
    max-spaces-inside-empty: -1

  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

  line-length:
    max: 120
