# Fangfrisch
Ralph Seichter <fangfrisch@seichter.de>
v0.0.7, {docdate}

:copyright: © Ralph Seichter
:encoding: UTF-8
:hyphens: en
:keywords: antivirus, clamav, fangfrisch, freshclam, refresh
:lang: en
:pagenums:
:publisher: Ralph Seichter
:sectanchors:
:sectnums:
:subject: Fangfrisch: Periodically update unofficial ClamAV signatures
////
:revnumber: 0.0.7
:revdate: 2020-02-16
:pdf-version: 1.7
:toc:
:toclevels: 3
:icons: font
:title-page:
:media: print
:source-highlighter: rouge
:rouge-style: base16.solarized.light
////

Copyright © 2020 Ralph Seichter

Fangfrisch (German for "freshly caught") is a sibling to the https://www.clamav.net[Clam Anti-Virus]
freshclam utility.
It allows downloading virus definition files that are not official ClamAV canon, e.g. from https://sanesecurity.com[Sanesecurity].

== Update strategy

Fangfrisch is expected to run periodically, for example using `cron`.
Download attempts are recorded in a database and new attempts are only made after the defined age threshold is reached.
Additionally, Fangfrisch will check digests first (if available), and only download virus definitions when their recorded digest changes, minimising transfer volumes.

== Usage

You can display command line arguments as follows:

----
python -m fangfrisch --help
----

----
usage: __main__.py [-h] [-c CONF] [-f] {dumpconf,initdb,refresh}

positional arguments:
  {dumpconf,initdb,refresh}
                        Action to perform

optional arguments:
  -h, --help            show this help message and exit
  -c CONF, --conf CONF  Configuration file
  -f, --force           Force action (default: False)
----

You can choose among following actions:

* *dumpconf*: Dump the effective configuration to stdout, combining both internal defaults and your own configuration.

* *initdb*: Create the database structure.
This needs to be run only once, before the first refresh.

* *refresh*: Refresh the configured URLs.
The `force` switch can be set to force downloads regardless of local file age.

Fangfrisch should never be run as `root`, but as your local ClamAV user (typically `clamav`).
An example crontab looks like this:

----
# minute hour day-of-month month day-of-week user command
*/30 * * * * clamav python -m fangfrisch --conf /etc/fangfrisch.conf refresh
----

== Configuration

A configuration file is mandatory and must contain a `db_url` entry.
For example:

----
include::../contrib/sample.conf[]
----

See https://docs.python.org/3.7/library/configparser.html[here] for a detailed description of the supported configuration file syntax with extended interpolation.
A description of SQLAlchemy's DB URL syntax is available https://docs.sqlalchemy.org/en/13/core/engines.html#supported-databases[here].
Typically, a local https://www.sqlite.org[SQLite] database will suffice.

Internal default values for Sanesecurity can be used by enabling the `[sanesecurity]` config section as shown above.
The resulting link:../contrib/sample-dump.conf[effective configuration] can be displayed using the `dumpconf`
action.

You can add your own sections for additional virus definition providers:

----
[exampleprovider]
enabled = yes
integrity_check = md5
# Set max age to 12 hours
max_age = 720
prefix = http://example.tld/clamav-unofficial/
url_eggs = ${prefix}eggs.ndb
url_spam = ${prefix}spam.hdb
----

Fangfrisch will scan enabled sections for lines with the prefix `url_` to determine download sources for virus definition files.
Supported schemas include FTP, HTTP and HTTPS.
The value of `integrity_check` determines both the expected filename suffix for digests and the hashing mechanism used for verification.

NOTE: Max age is specified in minutes.
Integrity checks can be turned off using the value `disabled`.
