from fangfrisch.config import BASE_URL
from fangfrisch.config import ENABLED
from fangfrisch.config import MAX_AGE

_config_sanesecurity = {
    'sanesecurity': {
        BASE_URL: 'http://ftp.swin.edu.au/sanesecurity/',
        ENABLED: '1',
        MAX_AGE: str(24 * 60),
        'url_badmacro': 'badmacro.ndb',
        'url_blurl': 'blurl.ndb',
        'url_bofhland_cracked_url': 'bofhland_cracked_URL.ndb',
        'url_bofhland_malware_attach': 'bofhland_malware_attach.hdb',
        'url_bofhland_malware_url': 'bofhland_malware_URL.ndb',
        'url_bofhland_phishing_url': 'bofhland_phishing_URL.ndb',
        'url_crdfam_clamav': 'crdfam.clamav.hdb',
        'url_doppelstern': 'doppelstern.ndb',
        'url_doppelstern-phishtank': 'doppelstern-phishtank.ndb',
        'url_doppelstern_hdb': 'doppelstern.hdb',
        'url_foxhole_all': 'foxhole_all.ndb',
        'url_foxhole_all_cdb': 'foxhole_all.cdb',
        'url_foxhole_filename': 'foxhole_filename.cdb',
        'url_foxhole_generic': 'foxhole_generic.cdb',
        'url_foxhole_js': 'foxhole_js.ndb',
        'url_foxhole_js_cdb': 'foxhole_js.cdb',
        'url_foxhole_mail': 'foxhole_mail.cdb',
        'url_junk': 'junk.ndb',
        'url_jurlbl': 'jurlbl.ndb',
        'url_jurlbla': 'jurlbla.ndb',
        'url_lott': 'lott.ndb',
        'url_malware.expert': 'malware.expert.ndb',
        'url_malware.expert_ndb': 'malware.expert.hdb',
        'url_phish': 'phish.ndb',
        'url_phishtank': 'phishtank.ndb',
        'url_porcupine': 'porcupine.ndb',
        'url_rogue': 'rogue.hdb',
        'url_scam': 'scam.ndb',
        'url_scamnailer': 'scamnailer.ndb',
        'url_spamattach': 'spamattach.hdb',
        'url_spamimg': 'spamimg.hdb',
        'url_spear': 'spear.ndb',
        'url_spearl': 'spearl.ndb',
        'url_winnow_attachments': 'winnow.attachments.hdb',
        'url_winnow_bad_cw': 'winnow_bad_cw.hdb',
        'url_winnow_extended_malware': 'winnow_extended_malware.hdb',
        'url_winnow_extended_malware_links': 'winnow_extended_malware_links.ndb',
        'url_winnow_malware': 'winnow_malware.hdb',
        'url_winnow_malware_links': 'winnow_malware_links.ndb',
        'url_winnow_phish_complete': 'winnow_phish_complete.ndb',
        'url_winnow_phish_complete_url': 'winnow_phish_complete_url.ndb',
        'url_winnow_spam_complete': 'winnow_spam_complete.ndb',
    }
}
